# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/MUX4T1_32_0/MUX4T1_32_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX4T1_32_0 || ORIG_REF_NAME==MUX4T1_32_0} -quiet] -quiet

# IP: ip/control_logic_0/control_logic_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_logic_0 || ORIG_REF_NAME==control_logic_0} -quiet] -quiet

# IP: ip/control_logic_0/src/PriorityEncoder_32/PriorityEncoder_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PriorityEncoder_32 || ORIG_REF_NAME==PriorityEncoder_32} -quiet] -quiet

# IP: ip/control_logic_0/src/dist_mem_gen_0/dist_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dist_mem_gen_0 || ORIG_REF_NAME==dist_mem_gen_0} -quiet] -quiet

# IP: ip/partial_store_0/partial_store_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==partial_store_0 || ORIG_REF_NAME==partial_store_0} -quiet] -quiet

# IP: ip/partial_store_0/src/MUX4T1_32_0/MUX4T1_32_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX4T1_32_0 || ORIG_REF_NAME==MUX4T1_32_0} -quiet] -quiet

# IP: ip/partial_store_0/src/MUX2T1_32_0/MUX2T1_32_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX2T1_32_0 || ORIG_REF_NAME==MUX2T1_32_0} -quiet] -quiet

# IP: ip/partial_load_0/partial_load_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==partial_load_0 || ORIG_REF_NAME==partial_load_0} -quiet] -quiet

# IP: ip/partial_load_0/src/MUX4T1_32_0/MUX4T1_32_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX4T1_32_0 || ORIG_REF_NAME==MUX4T1_32_0} -quiet] -quiet

# IP: ip/branch_comp_0/branch_comp_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==branch_comp_0 || ORIG_REF_NAME==branch_comp_0} -quiet] -quiet

# IP: ip/ImmGen_0/ImmGen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ImmGen_0 || ORIG_REF_NAME==ImmGen_0} -quiet] -quiet

# IP: ip/ImmGen_0/src/MUX8T1_32_0/MUX8T1_32_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX8T1_32_0 || ORIG_REF_NAME==MUX8T1_32_0} -quiet] -quiet

# IP: ip/ALU_0_1/ALU_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_0 || ORIG_REF_NAME==ALU_0} -quiet] -quiet

# IP: ip/ALU_0_1/src/MUX2T1_32_0/MUX2T1_32_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX2T1_32_0 || ORIG_REF_NAME==MUX2T1_32_0} -quiet] -quiet

# IP: ip/ALU_0_1/src/MUX16T1_32_0/MUX16T1_32_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX16T1_32_0 || ORIG_REF_NAME==MUX16T1_32_0} -quiet] -quiet

# IP: ip/RegFiles/RegFiles.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RegFiles || ORIG_REF_NAME==RegFiles} -quiet] -quiet

# XDC: ip/control_logic_0/src/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc
